//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTech.ServiceEmpleado {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEmpleado.IServiceEmpleado")]
    public interface IServiceEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/ListEmpleadoAsesores", ReplyAction="http://tempuri.org/IServiceEmpleado/ListEmpleadoAsesoresResponse")]
        ServicesTech.Dominio.Empleado[] ListEmpleadoAsesores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/ListEmpleadoAsesores", ReplyAction="http://tempuri.org/IServiceEmpleado/ListEmpleadoAsesoresResponse")]
        System.Threading.Tasks.Task<ServicesTech.Dominio.Empleado[]> ListEmpleadoAsesoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/GetInfoEmpleadoById", ReplyAction="http://tempuri.org/IServiceEmpleado/GetInfoEmpleadoByIdResponse")]
        ServicesTech.Dominio.Empleado GetInfoEmpleadoById(int EmployeeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/GetInfoEmpleadoById", ReplyAction="http://tempuri.org/IServiceEmpleado/GetInfoEmpleadoByIdResponse")]
        System.Threading.Tasks.Task<ServicesTech.Dominio.Empleado> GetInfoEmpleadoByIdAsync(int EmployeeeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEmpleadoChannel : WebTech.ServiceEmpleado.IServiceEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEmpleadoClient : System.ServiceModel.ClientBase<WebTech.ServiceEmpleado.IServiceEmpleado>, WebTech.ServiceEmpleado.IServiceEmpleado {
        
        public ServiceEmpleadoClient() {
        }
        
        public ServiceEmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicesTech.Dominio.Empleado[] ListEmpleadoAsesores() {
            return base.Channel.ListEmpleadoAsesores();
        }
        
        public System.Threading.Tasks.Task<ServicesTech.Dominio.Empleado[]> ListEmpleadoAsesoresAsync() {
            return base.Channel.ListEmpleadoAsesoresAsync();
        }
        
        public ServicesTech.Dominio.Empleado GetInfoEmpleadoById(int EmployeeeId) {
            return base.Channel.GetInfoEmpleadoById(EmployeeeId);
        }
        
        public System.Threading.Tasks.Task<ServicesTech.Dominio.Empleado> GetInfoEmpleadoByIdAsync(int EmployeeeId) {
            return base.Channel.GetInfoEmpleadoByIdAsync(EmployeeeId);
        }
    }
}
