//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTech.ServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceClient.IServiceClient")]
    public interface IServiceClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/ConsultDatosPersonal", ReplyAction="http://tempuri.org/IServiceClient/ConsultDatosPersonalResponse")]
        ServicesTech.Dominio.PersonaNatural ConsultDatosPersonal(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/ConsultDatosPersonal", ReplyAction="http://tempuri.org/IServiceClient/ConsultDatosPersonalResponse")]
        System.Threading.Tasks.Task<ServicesTech.Dominio.PersonaNatural> ConsultDatosPersonalAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/ConsultDatosCompany", ReplyAction="http://tempuri.org/IServiceClient/ConsultDatosCompanyResponse")]
        ServicesTech.Dominio.Empresa ConsultDatosCompany(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/ConsultDatosCompany", ReplyAction="http://tempuri.org/IServiceClient/ConsultDatosCompanyResponse")]
        System.Threading.Tasks.Task<ServicesTech.Dominio.Empresa> ConsultDatosCompanyAsync(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/InsertDataClient", ReplyAction="http://tempuri.org/IServiceClient/InsertDataClientResponse")]
        int InsertDataClient(ServicesTech.Dominio.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/InsertDataClient", ReplyAction="http://tempuri.org/IServiceClient/InsertDataClientResponse")]
        System.Threading.Tasks.Task<int> InsertDataClientAsync(ServicesTech.Dominio.Client client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceClientChannel : WebTech.ServiceClient.IServiceClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClientClient : System.ServiceModel.ClientBase<WebTech.ServiceClient.IServiceClient>, WebTech.ServiceClient.IServiceClient {
        
        public ServiceClientClient() {
        }
        
        public ServiceClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicesTech.Dominio.PersonaNatural ConsultDatosPersonal(string dni) {
            return base.Channel.ConsultDatosPersonal(dni);
        }
        
        public System.Threading.Tasks.Task<ServicesTech.Dominio.PersonaNatural> ConsultDatosPersonalAsync(string dni) {
            return base.Channel.ConsultDatosPersonalAsync(dni);
        }
        
        public ServicesTech.Dominio.Empresa ConsultDatosCompany(string RUC) {
            return base.Channel.ConsultDatosCompany(RUC);
        }
        
        public System.Threading.Tasks.Task<ServicesTech.Dominio.Empresa> ConsultDatosCompanyAsync(string RUC) {
            return base.Channel.ConsultDatosCompanyAsync(RUC);
        }
        
        public int InsertDataClient(ServicesTech.Dominio.Client client) {
            return base.Channel.InsertDataClient(client);
        }
        
        public System.Threading.Tasks.Task<int> InsertDataClientAsync(ServicesTech.Dominio.Client client) {
            return base.Channel.InsertDataClientAsync(client);
        }
    }
}
