//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTech.ServiceServicios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceServicios.IServiceServicios")]
    public interface IServiceServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceServicios/ListarTypeServices", ReplyAction="http://tempuri.org/IServiceServicios/ListarTypeServicesResponse")]
        ServicesTech.Dominio.TypeServices[] ListarTypeServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceServicios/ListarTypeServices", ReplyAction="http://tempuri.org/IServiceServicios/ListarTypeServicesResponse")]
        System.Threading.Tasks.Task<ServicesTech.Dominio.TypeServices[]> ListarTypeServicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceServicios/ListarServicesbyType", ReplyAction="http://tempuri.org/IServiceServicios/ListarServicesbyTypeResponse")]
        ServicesTech.Dominio.Services[] ListarServicesbyType(int TypeServicesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceServicios/ListarServicesbyType", ReplyAction="http://tempuri.org/IServiceServicios/ListarServicesbyTypeResponse")]
        System.Threading.Tasks.Task<ServicesTech.Dominio.Services[]> ListarServicesbyTypeAsync(int TypeServicesId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceServiciosChannel : WebTech.ServiceServicios.IServiceServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceServiciosClient : System.ServiceModel.ClientBase<WebTech.ServiceServicios.IServiceServicios>, WebTech.ServiceServicios.IServiceServicios {
        
        public ServiceServiciosClient() {
        }
        
        public ServiceServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicesTech.Dominio.TypeServices[] ListarTypeServices() {
            return base.Channel.ListarTypeServices();
        }
        
        public System.Threading.Tasks.Task<ServicesTech.Dominio.TypeServices[]> ListarTypeServicesAsync() {
            return base.Channel.ListarTypeServicesAsync();
        }
        
        public ServicesTech.Dominio.Services[] ListarServicesbyType(int TypeServicesId) {
            return base.Channel.ListarServicesbyType(TypeServicesId);
        }
        
        public System.Threading.Tasks.Task<ServicesTech.Dominio.Services[]> ListarServicesbyTypeAsync(int TypeServicesId) {
            return base.Channel.ListarServicesbyTypeAsync(TypeServicesId);
        }
    }
}
