//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTech.ServiceTechTeam {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTechTeam.IServiceDevTech")]
    public interface IServiceDevTech {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDevTech/ValidateAccessLogin", ReplyAction="http://tempuri.org/IServiceDevTech/ValidateAccessLoginResponse")]
        bool ValidateAccessLogin(string email, string passuser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDevTech/ValidateAccessLogin", ReplyAction="http://tempuri.org/IServiceDevTech/ValidateAccessLoginResponse")]
        System.Threading.Tasks.Task<bool> ValidateAccessLoginAsync(string email, string passuser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDevTech/ConsultDatosPersonal", ReplyAction="http://tempuri.org/IServiceDevTech/ConsultDatosPersonalResponse")]
        Tecactus.Api.Reniec.Person ConsultDatosPersonal(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDevTech/ConsultDatosPersonal", ReplyAction="http://tempuri.org/IServiceDevTech/ConsultDatosPersonalResponse")]
        System.Threading.Tasks.Task<Tecactus.Api.Reniec.Person> ConsultDatosPersonalAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDevTech/ConsultDatosCompany", ReplyAction="http://tempuri.org/IServiceDevTech/ConsultDatosCompanyResponse")]
        Tecactus.Api.Sunat.Company ConsultDatosCompany(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDevTech/ConsultDatosCompany", ReplyAction="http://tempuri.org/IServiceDevTech/ConsultDatosCompanyResponse")]
        System.Threading.Tasks.Task<Tecactus.Api.Sunat.Company> ConsultDatosCompanyAsync(string RUC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDevTechChannel : WebTech.ServiceTechTeam.IServiceDevTech, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDevTechClient : System.ServiceModel.ClientBase<WebTech.ServiceTechTeam.IServiceDevTech>, WebTech.ServiceTechTeam.IServiceDevTech {
        
        public ServiceDevTechClient() {
        }
        
        public ServiceDevTechClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDevTechClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDevTechClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDevTechClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateAccessLogin(string email, string passuser) {
            return base.Channel.ValidateAccessLogin(email, passuser);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateAccessLoginAsync(string email, string passuser) {
            return base.Channel.ValidateAccessLoginAsync(email, passuser);
        }
        
        public Tecactus.Api.Reniec.Person ConsultDatosPersonal(string dni) {
            return base.Channel.ConsultDatosPersonal(dni);
        }
        
        public System.Threading.Tasks.Task<Tecactus.Api.Reniec.Person> ConsultDatosPersonalAsync(string dni) {
            return base.Channel.ConsultDatosPersonalAsync(dni);
        }
        
        public Tecactus.Api.Sunat.Company ConsultDatosCompany(string RUC) {
            return base.Channel.ConsultDatosCompany(RUC);
        }
        
        public System.Threading.Tasks.Task<Tecactus.Api.Sunat.Company> ConsultDatosCompanyAsync(string RUC) {
            return base.Channel.ConsultDatosCompanyAsync(RUC);
        }
    }
}
