//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProjectTech.ServiceEmpleado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/ServicesTech.Dominio")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Active_EmployeeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsersIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string celular_EmployeeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Active_Employeee {
            get {
                return this.Active_EmployeeeField;
            }
            set {
                if ((object.ReferenceEquals(this.Active_EmployeeeField, value) != true)) {
                    this.Active_EmployeeeField = value;
                    this.RaisePropertyChanged("Active_Employeee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_Employee {
            get {
                return this.Apellido_EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_EmployeeField, value) != true)) {
                    this.Apellido_EmployeeField = value;
                    this.RaisePropertyChanged("Apellido_Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_Employee {
            get {
                return this.Email_EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_EmployeeField, value) != true)) {
                    this.Email_EmployeeField = value;
                    this.RaisePropertyChanged("Email_Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeeId {
            get {
                return this.EmployeeeIdField;
            }
            set {
                if ((this.EmployeeeIdField.Equals(value) != true)) {
                    this.EmployeeeIdField = value;
                    this.RaisePropertyChanged("EmployeeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Employee {
            get {
                return this.Nombre_EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_EmployeeField, value) != true)) {
                    this.Nombre_EmployeeField = value;
                    this.RaisePropertyChanged("Nombre_Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsersId {
            get {
                return this.UsersIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersIdField, value) != true)) {
                    this.UsersIdField = value;
                    this.RaisePropertyChanged("UsersId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string celular_Employee {
            get {
                return this.celular_EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.celular_EmployeeField, value) != true)) {
                    this.celular_EmployeeField = value;
                    this.RaisePropertyChanged("celular_Employee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEmpleado.IServiceEmpleado")]
    public interface IServiceEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/ListEmpleadoAsesores", ReplyAction="http://tempuri.org/IServiceEmpleado/ListEmpleadoAsesoresResponse")]
        UnitTestProjectTech.ServiceEmpleado.Empleado[] ListEmpleadoAsesores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/ListEmpleadoAsesores", ReplyAction="http://tempuri.org/IServiceEmpleado/ListEmpleadoAsesoresResponse")]
        System.Threading.Tasks.Task<UnitTestProjectTech.ServiceEmpleado.Empleado[]> ListEmpleadoAsesoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/GetInfoEmpleadoById", ReplyAction="http://tempuri.org/IServiceEmpleado/GetInfoEmpleadoByIdResponse")]
        UnitTestProjectTech.ServiceEmpleado.Empleado GetInfoEmpleadoById(int EmployeeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/GetInfoEmpleadoById", ReplyAction="http://tempuri.org/IServiceEmpleado/GetInfoEmpleadoByIdResponse")]
        System.Threading.Tasks.Task<UnitTestProjectTech.ServiceEmpleado.Empleado> GetInfoEmpleadoByIdAsync(int EmployeeeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEmpleadoChannel : UnitTestProjectTech.ServiceEmpleado.IServiceEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEmpleadoClient : System.ServiceModel.ClientBase<UnitTestProjectTech.ServiceEmpleado.IServiceEmpleado>, UnitTestProjectTech.ServiceEmpleado.IServiceEmpleado {
        
        public ServiceEmpleadoClient() {
        }
        
        public ServiceEmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnitTestProjectTech.ServiceEmpleado.Empleado[] ListEmpleadoAsesores() {
            return base.Channel.ListEmpleadoAsesores();
        }
        
        public System.Threading.Tasks.Task<UnitTestProjectTech.ServiceEmpleado.Empleado[]> ListEmpleadoAsesoresAsync() {
            return base.Channel.ListEmpleadoAsesoresAsync();
        }
        
        public UnitTestProjectTech.ServiceEmpleado.Empleado GetInfoEmpleadoById(int EmployeeeId) {
            return base.Channel.GetInfoEmpleadoById(EmployeeeId);
        }
        
        public System.Threading.Tasks.Task<UnitTestProjectTech.ServiceEmpleado.Empleado> GetInfoEmpleadoByIdAsync(int EmployeeeId) {
            return base.Channel.GetInfoEmpleadoByIdAsync(EmployeeeId);
        }
    }
}
