//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProjectTech.ServiceUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioModel", Namespace="http://schemas.datacontract.org/2004/07/ServicesTech.Dominio")]
    [System.SerializableAttribute()]
    public partial class UsuarioModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Active_EmployeeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PK_empleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Active_Employeee {
            get {
                return this.Active_EmployeeeField;
            }
            set {
                if ((object.ReferenceEquals(this.Active_EmployeeeField, value) != true)) {
                    this.Active_EmployeeeField = value;
                    this.RaisePropertyChanged("Active_Employeee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_Employee {
            get {
                return this.Apellido_EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_EmployeeField, value) != true)) {
                    this.Apellido_EmployeeField = value;
                    this.RaisePropertyChanged("Apellido_Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_Employee {
            get {
                return this.Email_EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_EmployeeField, value) != true)) {
                    this.Email_EmployeeField = value;
                    this.RaisePropertyChanged("Email_Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Employee {
            get {
                return this.Nombre_EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_EmployeeField, value) != true)) {
                    this.Nombre_EmployeeField = value;
                    this.RaisePropertyChanged("Nombre_Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PK_empleado {
            get {
                return this.PK_empleadoField;
            }
            set {
                if ((this.PK_empleadoField.Equals(value) != true)) {
                    this.PK_empleadoField = value;
                    this.RaisePropertyChanged("PK_empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RolId {
            get {
                return this.RolIdField;
            }
            set {
                if ((this.RolIdField.Equals(value) != true)) {
                    this.RolIdField = value;
                    this.RaisePropertyChanged("RolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RolNombre {
            get {
                return this.RolNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.RolNombreField, value) != true)) {
                    this.RolNombreField = value;
                    this.RaisePropertyChanged("RolNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.IServiceUsuario")]
    public interface IServiceUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ValidateAccessLogin", ReplyAction="http://tempuri.org/IServiceUsuario/ValidateAccessLoginResponse")]
        int ValidateAccessLogin(string email, string passuser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ValidateAccessLogin", ReplyAction="http://tempuri.org/IServiceUsuario/ValidateAccessLoginResponse")]
        System.Threading.Tasks.Task<int> ValidateAccessLoginAsync(string email, string passuser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/GetDatabyUserTech", ReplyAction="http://tempuri.org/IServiceUsuario/GetDatabyUserTechResponse")]
        UnitTestProjectTech.ServiceUsuario.UsuarioModel GetDatabyUserTech(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/GetDatabyUserTech", ReplyAction="http://tempuri.org/IServiceUsuario/GetDatabyUserTechResponse")]
        System.Threading.Tasks.Task<UnitTestProjectTech.ServiceUsuario.UsuarioModel> GetDatabyUserTechAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUsuarioChannel : UnitTestProjectTech.ServiceUsuario.IServiceUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUsuarioClient : System.ServiceModel.ClientBase<UnitTestProjectTech.ServiceUsuario.IServiceUsuario>, UnitTestProjectTech.ServiceUsuario.IServiceUsuario {
        
        public ServiceUsuarioClient() {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ValidateAccessLogin(string email, string passuser) {
            return base.Channel.ValidateAccessLogin(email, passuser);
        }
        
        public System.Threading.Tasks.Task<int> ValidateAccessLoginAsync(string email, string passuser) {
            return base.Channel.ValidateAccessLoginAsync(email, passuser);
        }
        
        public UnitTestProjectTech.ServiceUsuario.UsuarioModel GetDatabyUserTech(string username) {
            return base.Channel.GetDatabyUserTech(username);
        }
        
        public System.Threading.Tasks.Task<UnitTestProjectTech.ServiceUsuario.UsuarioModel> GetDatabyUserTechAsync(string username) {
            return base.Channel.GetDatabyUserTechAsync(username);
        }
    }
}
