//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTech.ServiceUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.IServiceUsuario")]
    public interface IServiceUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ValidateAccessLogin", ReplyAction="http://tempuri.org/IServiceUsuario/ValidateAccessLoginResponse")]
        int ValidateAccessLogin(string email, string passuser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ValidateAccessLogin", ReplyAction="http://tempuri.org/IServiceUsuario/ValidateAccessLoginResponse")]
        System.Threading.Tasks.Task<int> ValidateAccessLoginAsync(string email, string passuser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/GetDatabyUserTech", ReplyAction="http://tempuri.org/IServiceUsuario/GetDatabyUserTechResponse")]
        ServicesTech.Dominio.UsuarioModel GetDatabyUserTech(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/GetDatabyUserTech", ReplyAction="http://tempuri.org/IServiceUsuario/GetDatabyUserTechResponse")]
        System.Threading.Tasks.Task<ServicesTech.Dominio.UsuarioModel> GetDatabyUserTechAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUsuarioChannel : WebTech.ServiceUsuario.IServiceUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUsuarioClient : System.ServiceModel.ClientBase<WebTech.ServiceUsuario.IServiceUsuario>, WebTech.ServiceUsuario.IServiceUsuario {
        
        public ServiceUsuarioClient() {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ValidateAccessLogin(string email, string passuser) {
            return base.Channel.ValidateAccessLogin(email, passuser);
        }
        
        public System.Threading.Tasks.Task<int> ValidateAccessLoginAsync(string email, string passuser) {
            return base.Channel.ValidateAccessLoginAsync(email, passuser);
        }
        
        public ServicesTech.Dominio.UsuarioModel GetDatabyUserTech(string username) {
            return base.Channel.GetDatabyUserTech(username);
        }
        
        public System.Threading.Tasks.Task<ServicesTech.Dominio.UsuarioModel> GetDatabyUserTechAsync(string username) {
            return base.Channel.GetDatabyUserTechAsync(username);
        }
    }
}
